import { Router, type IRouter } from "express";
import healthRouter from "./health";
import trainerWorkspaceRouter from "./trainerWorkspace";
import engagementRouter from "./engagement";
import assessmentRouter from "./assessment";
import ptDashboardRouter from "./ptDashboard";
import profileRouter from "./profile";
import dashboardRouter from "./dashboard";
import gymsRouter from "./gyms";
import classesRouter from "./classes";
import membershipsRouter from "./memberships";
import bookingsRouter from "./bookings";
import trainersRouter from "./trainers";
import trainerBookingsRouter from "./trainerBookings";
import packageBookingsRouter from "./packageBookings";
import walletRouter from "./wallet";
import referralsRouter from "./referrals";
import adminRouter from "./admin";
import partnerRouter from "./partner";
import staffRouter from "./staff";
import storeRouter from "./store";
import locationsRouter from "./locations";
import storageRouter from "./storage";
import leadsRouter from "./leads";
import blogsRouter from "./blogs";
import notificationsRouter from "./notifications";
import ticketsRouter from "./tickets";
import complaintsRouter from "./complaints";
import aiRouter from "./ai";
import agencyRouter from "./agency";
import trackingRouter from "./tracking";
import challengesRouter from "./challenges";
import homeSlidesRouter from "./homeSlides";
import faqsRouter from "./faqs";
import couponsRouter from "./coupons";
import messagingRouter from "./messaging";
import settingsRouter from "./settings";
import webhooksRouter from "./webhooks";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profileRouter);
router.use(dashboardRouter);
router.use(gymsRouter);
router.use(classesRouter);
router.use(membershipsRouter);
router.use(bookingsRouter);
router.use(trainersRouter);
router.use(trainerBookingsRouter);
router.use(packageBookingsRouter);
router.use(walletRouter);
router.use(referralsRouter);
router.use(adminRouter);
router.use(partnerRouter);
router.use(staffRouter);
router.use(trainerWorkspaceRouter);
router.use(engagementRouter);
router.use(assessmentRouter);
router.use(ptDashboardRouter);
router.use(storeRouter);
router.use(locationsRouter);
router.use(storageRouter);
router.use(leadsRouter);
router.use(blogsRouter);
router.use(notificationsRouter);
router.use(ticketsRouter);
router.use(complaintsRouter);
router.use(aiRouter);
router.use(agencyRouter);
router.use(trackingRouter);
router.use(challengesRouter);
router.use(homeSlidesRouter);
router.use(faqsRouter);
router.use(couponsRouter);
router.use(messagingRouter);
router.use(settingsRouter);
router.use(webhooksRouter);

export default router;
