import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profileRouter from "./profile";
import dashboardRouter from "./dashboard";
import gymsRouter from "./gyms";
import classesRouter from "./classes";
import membershipsRouter from "./memberships";
import bookingsRouter from "./bookings";
import trainersRouter from "./trainers";
import walletRouter from "./wallet";
import adminRouter from "./admin";
import partnerRouter from "./partner";
import staffRouter from "./staff";
import storeRouter from "./store";
import locationsRouter from "./locations";
import storageRouter from "./storage";
import leadsRouter from "./leads";
import blogsRouter from "./blogs";
import notificationsRouter from "./notifications";
import ticketsRouter from "./tickets";
import aiRouter from "./ai";
import agencyRouter from "./agency";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profileRouter);
router.use(dashboardRouter);
router.use(gymsRouter);
router.use(classesRouter);
router.use(membershipsRouter);
router.use(bookingsRouter);
router.use(trainersRouter);
router.use(walletRouter);
router.use(adminRouter);
router.use(partnerRouter);
router.use(staffRouter);
router.use(storeRouter);
router.use(locationsRouter);
router.use(storageRouter);
router.use(leadsRouter);
router.use(blogsRouter);
router.use(notificationsRouter);
router.use(ticketsRouter);
router.use(aiRouter);
router.use(agencyRouter);

export default router;
