import type { Feather } from "@expo/vector-icons";

export type Difficulty = "Beginner" | "Intermediate" | "Advanced";

export type ExerciseCategory = {
  id: string;
  label: string;
  icon: keyof typeof Feather.glyphMap;
};

export type Exercise = {
  slug: string;
  name: string;
  categoryId: string;
  muscle: string;
  equipment: string;
  difficulty: Difficulty;
  caloriesPerSet: number;
  sets: number;
  reps: string;
  rest: string;
  icon: keyof typeof Feather.glyphMap;
  summary: string;
  instructions: string[];
  mistakes: string[];
  alternatives: string[];
};

export const EXERCISE_CATEGORIES: ExerciseCategory[] = [
  { id: "chest", label: "Chest", icon: "shield" },
  { id: "back", label: "Back", icon: "triangle" },
  { id: "legs", label: "Legs", icon: "trello" },
  { id: "shoulders", label: "Shoulders", icon: "umbrella" },
  { id: "arms", label: "Arms", icon: "zap" },
  { id: "core", label: "Core", icon: "target" },
  { id: "cardio", label: "Cardio", icon: "heart" },
  { id: "fullbody", label: "Full Body", icon: "activity" },
];

export const EXERCISES: Exercise[] = [
  {
    slug: "bench-press",
    name: "Barbell Bench Press",
    categoryId: "chest",
    muscle: "Chest, Triceps, Front Delts",
    equipment: "Barbell + Bench",
    difficulty: "Intermediate",
    caloriesPerSet: 12,
    sets: 4,
    reps: "8–10",
    rest: "90 sec",
    icon: "shield",
    summary:
      "The king of upper-body pressing — builds chest size, pressing power and triceps strength.",
    instructions: [
      "Lie flat, eyes under the bar, feet planted firmly on the floor.",
      "Grip slightly wider than shoulder width and unrack with straight arms.",
      "Lower the bar under control to mid-chest, elbows at ~45°.",
      "Press explosively back up without flaring the elbows or bouncing.",
    ],
    mistakes: [
      "Bouncing the bar off the chest.",
      "Flaring elbows straight out to 90°.",
      "Lifting the hips off the bench.",
    ],
    alternatives: ["dumbbell-press", "push-up"],
  },
  {
    slug: "dumbbell-press",
    name: "Incline Dumbbell Press",
    categoryId: "chest",
    muscle: "Upper Chest, Shoulders",
    equipment: "Dumbbells + Bench",
    difficulty: "Beginner",
    caloriesPerSet: 10,
    sets: 3,
    reps: "10–12",
    rest: "75 sec",
    icon: "shield",
    summary:
      "Targets the upper chest for a fuller, balanced look with a greater range of motion.",
    instructions: [
      "Set the bench to a 30° incline and sit with dumbbells on your thighs.",
      "Kick the weights up and press them over your upper chest.",
      "Lower slowly until you feel a stretch, then press back up.",
    ],
    mistakes: ["Setting the incline too steep.", "Clanging the dumbbells at the top."],
    alternatives: ["bench-press", "push-up"],
  },
  {
    slug: "push-up",
    name: "Push-Up",
    categoryId: "chest",
    muscle: "Chest, Triceps, Core",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    caloriesPerSet: 8,
    sets: 3,
    reps: "12–20",
    rest: "60 sec",
    icon: "shield",
    summary:
      "A no-equipment classic that builds the chest, triceps and a braced core anywhere.",
    instructions: [
      "Hands just wider than shoulders, body in a straight line.",
      "Lower until your chest is an inch off the floor.",
      "Press up while keeping your core and glutes tight.",
    ],
    mistakes: ["Sagging hips.", "Half range of motion.", "Flaring elbows."],
    alternatives: ["bench-press", "dumbbell-press"],
  },
  {
    slug: "deadlift",
    name: "Conventional Deadlift",
    categoryId: "back",
    muscle: "Back, Glutes, Hamstrings",
    equipment: "Barbell",
    difficulty: "Advanced",
    caloriesPerSet: 16,
    sets: 4,
    reps: "5",
    rest: "120 sec",
    icon: "triangle",
    summary:
      "The ultimate full-posterior-chain strength builder. Heavy, technical and hugely rewarding.",
    instructions: [
      "Stand with mid-foot under the bar, shins close.",
      "Hinge and grip just outside your knees, chest up, back flat.",
      "Drive through the floor and stand tall, locking hips and knees together.",
      "Lower under control by pushing the hips back first.",
    ],
    mistakes: ["Rounding the lower back.", "Jerking the bar off the floor.", "Hyperextending at the top."],
    alternatives: ["lat-pulldown", "barbell-row"],
  },
  {
    slug: "barbell-row",
    name: "Barbell Bent-Over Row",
    categoryId: "back",
    muscle: "Lats, Upper Back, Biceps",
    equipment: "Barbell",
    difficulty: "Intermediate",
    caloriesPerSet: 11,
    sets: 4,
    reps: "8–10",
    rest: "90 sec",
    icon: "triangle",
    summary: "Builds a thick, wide back and strong pulling muscles for better posture.",
    instructions: [
      "Hinge at the hips to ~45°, back flat, knees soft.",
      "Pull the bar to your lower ribs, squeezing the shoulder blades.",
      "Lower under control without rounding the back.",
    ],
    mistakes: ["Using momentum to heave the weight.", "Standing too upright."],
    alternatives: ["lat-pulldown", "deadlift"],
  },
  {
    slug: "lat-pulldown",
    name: "Lat Pulldown",
    categoryId: "back",
    muscle: "Lats, Biceps",
    equipment: "Cable Machine",
    difficulty: "Beginner",
    caloriesPerSet: 9,
    sets: 3,
    reps: "10–12",
    rest: "75 sec",
    icon: "triangle",
    summary: "A beginner-friendly way to build the wide 'V-taper' back muscles.",
    instructions: [
      "Grip the bar wider than shoulders and sit tall.",
      "Pull the bar to your upper chest, driving elbows down.",
      "Control the bar back up to a full stretch.",
    ],
    mistakes: ["Leaning back too far.", "Pulling behind the neck."],
    alternatives: ["barbell-row", "push-up"],
  },
  {
    slug: "back-squat",
    name: "Barbell Back Squat",
    categoryId: "legs",
    muscle: "Quads, Glutes, Core",
    equipment: "Barbell + Rack",
    difficulty: "Intermediate",
    caloriesPerSet: 15,
    sets: 4,
    reps: "6–8",
    rest: "120 sec",
    icon: "trello",
    summary: "The foundational leg builder for size, strength and athleticism.",
    instructions: [
      "Bar on upper traps, feet shoulder-width, toes slightly out.",
      "Brace your core and sit down between your hips.",
      "Descend until thighs are at least parallel, knees tracking toes.",
      "Drive up through mid-foot to standing.",
    ],
    mistakes: ["Knees caving in.", "Heels lifting.", "Rounding the back at the bottom."],
    alternatives: ["goblet-squat", "lunge"],
  },
  {
    slug: "goblet-squat",
    name: "Goblet Squat",
    categoryId: "legs",
    muscle: "Quads, Glutes",
    equipment: "Dumbbell / Kettlebell",
    difficulty: "Beginner",
    caloriesPerSet: 10,
    sets: 3,
    reps: "12–15",
    rest: "60 sec",
    icon: "trello",
    summary: "A beginner-friendly squat that teaches great depth and an upright torso.",
    instructions: [
      "Hold a dumbbell vertically against your chest.",
      "Squat down keeping your chest tall and elbows inside the knees.",
      "Stand back up squeezing the glutes.",
    ],
    mistakes: ["Leaning forward.", "Not reaching depth."],
    alternatives: ["back-squat", "lunge"],
  },
  {
    slug: "lunge",
    name: "Walking Lunge",
    categoryId: "legs",
    muscle: "Quads, Glutes, Hamstrings",
    equipment: "Bodyweight / Dumbbells",
    difficulty: "Beginner",
    caloriesPerSet: 11,
    sets: 3,
    reps: "12 each leg",
    rest: "60 sec",
    icon: "trello",
    summary: "Single-leg work that builds balance, symmetry and lower-body endurance.",
    instructions: [
      "Step forward and lower until both knees are at ~90°.",
      "Keep your front knee over the ankle, torso tall.",
      "Push through the front heel to step into the next lunge.",
    ],
    mistakes: ["Front knee collapsing inward.", "Short, choppy steps."],
    alternatives: ["goblet-squat", "back-squat"],
  },
  {
    slug: "overhead-press",
    name: "Standing Overhead Press",
    categoryId: "shoulders",
    muscle: "Shoulders, Triceps",
    equipment: "Barbell",
    difficulty: "Intermediate",
    caloriesPerSet: 11,
    sets: 4,
    reps: "6–8",
    rest: "90 sec",
    icon: "umbrella",
    summary: "Builds capped, strong shoulders and a rock-solid overhead position.",
    instructions: [
      "Bar on front delts, grip just outside shoulders, core braced.",
      "Press straight overhead, moving the head back slightly out of the way.",
      "Lock out with the bar over mid-foot, then lower under control.",
    ],
    mistakes: ["Over-arching the lower back.", "Pressing the bar forward instead of up."],
    alternatives: ["lateral-raise", "push-up"],
  },
  {
    slug: "lateral-raise",
    name: "Dumbbell Lateral Raise",
    categoryId: "shoulders",
    muscle: "Side Delts",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    caloriesPerSet: 7,
    sets: 3,
    reps: "12–15",
    rest: "45 sec",
    icon: "umbrella",
    summary: "The go-to isolation move for wide, rounded shoulders.",
    instructions: [
      "Hold light dumbbells at your sides, slight bend in the elbows.",
      "Raise out to the sides until arms are parallel to the floor.",
      "Lower slowly — control beats heavy weight here.",
    ],
    mistakes: ["Swinging with momentum.", "Going too heavy and shrugging."],
    alternatives: ["overhead-press"],
  },
  {
    slug: "bicep-curl",
    name: "Dumbbell Bicep Curl",
    categoryId: "arms",
    muscle: "Biceps",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    caloriesPerSet: 6,
    sets: 3,
    reps: "10–12",
    rest: "45 sec",
    icon: "zap",
    summary: "Classic arm builder for bigger, stronger biceps.",
    instructions: [
      "Stand tall, dumbbells at your sides, palms forward.",
      "Curl up while keeping the elbows pinned to your ribs.",
      "Squeeze at the top, then lower slowly.",
    ],
    mistakes: ["Swinging the torso.", "Moving the elbows forward."],
    alternatives: ["tricep-dip"],
  },
  {
    slug: "tricep-dip",
    name: "Bench Tricep Dip",
    categoryId: "arms",
    muscle: "Triceps",
    equipment: "Bench / Bodyweight",
    difficulty: "Beginner",
    caloriesPerSet: 7,
    sets: 3,
    reps: "12–15",
    rest: "45 sec",
    icon: "zap",
    summary: "Builds the triceps — the muscle that makes up most of your arm size.",
    instructions: [
      "Hands on a bench behind you, legs out in front.",
      "Lower your hips until your elbows reach ~90°.",
      "Press back up by straightening the arms.",
    ],
    mistakes: ["Shrugging the shoulders up.", "Going too low and straining the shoulders."],
    alternatives: ["push-up", "bicep-curl"],
  },
  {
    slug: "plank",
    name: "Forearm Plank",
    categoryId: "core",
    muscle: "Core, Abs",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    caloriesPerSet: 5,
    sets: 3,
    reps: "30–60 sec",
    rest: "45 sec",
    icon: "target",
    summary: "Builds deep core stability and a stronger, more resilient midsection.",
    instructions: [
      "Forearms under shoulders, body in a straight line.",
      "Squeeze glutes and brace the abs hard.",
      "Hold without letting the hips sag or pike.",
    ],
    mistakes: ["Hips sagging.", "Holding your breath.", "Looking up and straining the neck."],
    alternatives: ["hanging-leg-raise"],
  },
  {
    slug: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    categoryId: "core",
    muscle: "Lower Abs, Hip Flexors",
    equipment: "Pull-up Bar",
    difficulty: "Intermediate",
    caloriesPerSet: 8,
    sets: 3,
    reps: "10–15",
    rest: "60 sec",
    icon: "target",
    summary: "An advanced ab builder that targets the hard-to-train lower abs.",
    instructions: [
      "Hang from a bar with a tight grip and braced shoulders.",
      "Raise your legs until they're parallel to the floor (or higher).",
      "Lower slowly without swinging.",
    ],
    mistakes: ["Using momentum to swing.", "Bending the legs to cheat."],
    alternatives: ["plank"],
  },
  {
    slug: "burpee",
    name: "Burpee",
    categoryId: "cardio",
    muscle: "Full Body, Heart",
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    caloriesPerSet: 14,
    sets: 4,
    reps: "10–15",
    rest: "45 sec",
    icon: "heart",
    summary: "A brutal full-body conditioning move that spikes the heart rate fast.",
    instructions: [
      "Drop into a squat and place your hands on the floor.",
      "Kick your feet back into a push-up position and lower your chest.",
      "Explode back up and jump with the arms overhead.",
    ],
    mistakes: ["Sagging hips in the push-up.", "Skipping the chest-to-floor."],
    alternatives: ["mountain-climber", "jump-rope"],
  },
  {
    slug: "mountain-climber",
    name: "Mountain Climber",
    categoryId: "cardio",
    muscle: "Core, Heart, Shoulders",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    caloriesPerSet: 10,
    sets: 4,
    reps: "30 sec",
    rest: "30 sec",
    icon: "heart",
    summary: "A fast core-and-cardio move that needs zero equipment.",
    instructions: [
      "Start in a high plank, hands under shoulders.",
      "Drive one knee toward your chest, then switch quickly.",
      "Keep the hips low and the core braced throughout.",
    ],
    mistakes: ["Bouncing the hips up.", "Going too fast and losing form."],
    alternatives: ["burpee", "jump-rope"],
  },
  {
    slug: "jump-rope",
    name: "Jump Rope",
    categoryId: "cardio",
    muscle: "Calves, Heart",
    equipment: "Jump Rope",
    difficulty: "Beginner",
    caloriesPerSet: 13,
    sets: 4,
    reps: "60 sec",
    rest: "30 sec",
    icon: "heart",
    summary: "Efficient cardio that builds footwork, coordination and endurance.",
    instructions: [
      "Hold the handles lightly, elbows close to the body.",
      "Turn the rope with the wrists, not the arms.",
      "Jump just an inch off the floor, landing softly.",
    ],
    mistakes: ["Jumping too high.", "Swinging from the shoulders."],
    alternatives: ["mountain-climber", "burpee"],
  },
  {
    slug: "kettlebell-swing",
    name: "Kettlebell Swing",
    categoryId: "fullbody",
    muscle: "Glutes, Hamstrings, Core",
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    caloriesPerSet: 13,
    sets: 4,
    reps: "15–20",
    rest: "60 sec",
    icon: "activity",
    summary: "An explosive hip-hinge move that builds power, conditioning and a strong posterior chain.",
    instructions: [
      "Hinge at the hips and grip the kettlebell with both hands.",
      "Hike it back between your legs, then snap the hips forward.",
      "Let the bell float to chest height — power comes from the hips, not the arms.",
    ],
    mistakes: ["Squatting instead of hinging.", "Lifting with the arms.", "Over-arching at the top."],
    alternatives: ["deadlift", "goblet-squat"],
  },
  {
    slug: "thruster",
    name: "Dumbbell Thruster",
    categoryId: "fullbody",
    muscle: "Legs, Shoulders, Core",
    equipment: "Dumbbells",
    difficulty: "Advanced",
    caloriesPerSet: 15,
    sets: 4,
    reps: "10–12",
    rest: "75 sec",
    icon: "activity",
    summary: "A squat-to-press combo that trains the whole body and torches calories.",
    instructions: [
      "Hold dumbbells at your shoulders and drop into a front squat.",
      "Drive up explosively and press the weights overhead in one motion.",
      "Lower back to the shoulders and repeat.",
    ],
    mistakes: ["Pausing between the squat and press.", "Pressing before standing fully."],
    alternatives: ["overhead-press", "back-squat"],
  },
];

export function getExercise(slug: string): Exercise | undefined {
  return EXERCISES.find((e) => e.slug === slug);
}

export function exercisesByCategory(categoryId: string | null): Exercise[] {
  if (!categoryId) return EXERCISES;
  return EXERCISES.filter((e) => e.categoryId === categoryId);
}

export function categoryLabel(categoryId: string): string {
  return EXERCISE_CATEGORIES.find((c) => c.id === categoryId)?.label ?? categoryId;
}
